name: Release Service

on:
  push:
    tags:
      - 'v*.*'

jobs:
  release:
    uses: start9labs/shared-workflows/.github/workflows/releaseService.yml@master
    # with:
    #   REGISTRY: https://my-custom-registry.example.com
    secrets:
      DEV_KEY: ${{ secrets.DEV_KEY }}
    permissions:
      contents: write
